import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { AblyProvider } from "@/lib/ablyContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Spotify BlindTest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`container`}>
        <AblyProvider>
          {children} {/* L'application aura accès à Ably */}
        </AblyProvider>
      </body>
    </html>
  );
}
